# -*- coding: utf-8 -*-
"""python day 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LRKx_MAG8wvbnwqVFvVHmJHJK54SIFQ4
"""

# sum of n numbers
sum=0;
i=1;
a=int(input("enter the value"))
while i<=a:
  sum=sum+i;
  i=i+1;
print("the value of sum=",sum)

# to find prime or not
num = int(input("Enter a number:"))
if num<=1:
    print(num,"is not a prime number")
else:
    for i in range(2,num):
        if(num%i)==0:
            print(num, "is not a prime number")
            break
    else:
            print(num, "is a prime number")